# Generated by Django 5.2.6 on 2025-10-11 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outage',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='outages.community'),
        ),
        migrations.AlterField(
            model_name='outage',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
