# Generated by Django 5.2.6 on 2025-09-14 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outage',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outage',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_outages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outage',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outage',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_outages', to=settings.AUTH_USER_MODEL),
        ),
    ]
