# Generated by Django 5.2.8 on 2025-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0002_alter_outage_community_alter_outage_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outage',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
